# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  accelq-connect: accelq/accelq-connect@1.0.0
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - accelq-connect/accelq-ci:
          agent-name: "POC"
          job-id: "340897"
          password: "QdlTWUx"
          project-name: "Vivek Qbank"
          tenant: "demotenant"
          url: "https://poc.accelq.io"
          user: "vivekop@yopmail.com"
